name: CI Linux
on:
  workflow_dispatch:

jobs:
  build-binaries-unix:
    name: Build unix lib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ffmpeg-build repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdrm-dev libegl1-mesa-dev libsdl2-dev libxxhash-dev glslang-dev libvulkan-dev liblcms2-dev build-essential libx11-xcb-dev libxkbcommon-dev libwayland-dev libxrandr-dev cmake pkg-config nasm yasm

      - name: Download Vulkan SDK
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.268-jammy.list https://packages.lunarg.com/vulkan/1.3.268/lunarg-vulkan-1.3.268-jammy.list
          sudo apt-get update
          sudo apt-get install -y vulkan-sdk

      - name: Install Meson and Ninja
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --upgrade meson==1.3.0
          pip3 install --upgrade ninja==1.11.1

      - name: Checkout FFmpeg at Tag n6.1.1
        uses: actions/checkout@v3
        with:
          repository: 'FFmpeg/FFmpeg'
          ref: 'n6.1.1'
          path: 'ffmpeg-6.1.1'

      - name: Apply FFmpeg pacthes
        run: |
          cd ffmpeg-6.1.1
          git apply ../patches/vaapi_h264.patch

      - name: Check Patch Application
        run: |
          git diff

      - name: Configure FFmpeg
        run: |
          cd ffmpeg-6.1.1
          export CFLAGS="-fPIC"
          sudo ./configure --disable-all --disable-gpl --disable-iconv --enable-libdrm --enable-vulkan --enable-static --enable-pic --enable-libdrm --enable-avcodec --enable-avformat --enable-decoder=h264 --enable-decoder=hevc --enable-hwaccel=h264_vaapi --enable-hwaccel=hevc_vaapi --enable-hwaccel=h264_vdpau --enable-hwaccel=hevc_vdpau --enable-hwaccel=h264_vulkan --enable-hwaccel=hevc_vulkan --enable-hwaccel=h264_cuda --enable-hwaccel=hevc_cuda --extra-ldexeflags="-pie"

      - name: Build FFmpeg
        run: |
          cd ffmpeg-6.1.1
          make -j$(nproc)

      - name: Upload FFmpeg build
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-build-artifact
          path: ffmpeg-6.1.1
