name: CI Linux
on:
  workflow_dispatch:

jobs:
  build-binaries-unix:
    name: Build unix lib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ffmpeg-build repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdrm-dev libegl1-mesa-dev libsdl2-dev libxxhash-dev glslang-dev libvulkan-dev liblcms2-dev build-essential libx11-xcb-dev libxkbcommon-dev libwayland-dev libxrandr-dev cmake pkg-config nasm yasm

      - name: Install vulkan stuff
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install libglm-dev cmake libxcb-dri3-0 libxcb-present0 libpciaccess0 \
          libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev libx11-dev g++ gcc g++-multilib \
          libmirclient-dev libwayland-dev libxrandr-dev libxcb-randr0-dev libxcb-ewmh-dev \
          git python python3 bison libx11-xcb-dev liblz4-dev libzstd-dev python3-distutils \
          ocaml-core ninja-build pkg-config libxml2-dev wayland-protocols python3-jsonschema

      - name: Install Meson and Ninja
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --upgrade meson==1.3.0
          pip3 install --upgrade ninja==1.11.1

      - name: Download FFmpeg
        run: |
          wget https://ffmpeg.org/releases/ffmpeg-6.1.tar.xz
          tar xvf ffmpeg-6.1.tar.xz
          cd ffmpeg-6.1

      - name: Configure FFmpeg
        run: |
          cd ffmpeg-6.1
          export CFLAGS="-fPIC"
          sudo ./configure --disable-all --disable-gpl --disable-iconv --enable-libdrm --enable-vulkan --enable-static --enable-pic --enable-libdrm --enable-avcodec --enable-avformat --enable-decoder=h264 --enable-decoder=hevc --enable-hwaccel=h264_vaapi --enable-hwaccel=hevc_vaapi --enable-hwaccel=h264_vdpau --enable-hwaccel=hevc_vdpau --enable-hwaccel=h264_vulkan --enable-hwaccel=hevc_vulkan --enable-hwaccel=h264_cuda --enable-hwaccel=hevc_cuda --extra-ldexeflags="-pie"

      - name: Build FFmpeg
        run: |
          cd ffmpeg-6.1
          make -j$(nproc)

      - name: Upload FFmpeg build
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-build-artifact
          path: ffmpeg-6.1
