name: CI Linux
on:
  workflow_dispatch:

jobs:
  build-binaries-unix:
    name: Build unix lib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fffmpeg-build repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libavcodec-dev libavformat-dev libegl1-mesa-dev libsdl2-dev libxxhash-dev glslang-dev libvulkan-dev liblcms2-dev build-essential libx11-xcb-dev libxkbcommon-dev libwayland-dev libxrandr-dev cmake

      - name: Install xbxc dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxcb1-dev libxcb-randr0-dev libxcb-keysyms1-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-xkb-dev

      - name: Install Meson and Ninja
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --upgrade meson==1.3.0
          pip3 install --upgrade ninja==1.11.1
          
          

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-libplacebo-jni-artifact-64bit
          path: ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native-64.so
