name: CI Windows
on:
  workflow_dispatch:

jobs:
  build-binaries-windows:
    name: Build Windows lib
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - sys: UCRT64
            env: ucrt-x86_64
            arch: 64bit
            archValue: 64
            archAltValue: x64
          - sys: MINGW32
            env: i686
            arch: 32bit
            archValue: 32
            archAltValue: x32

    steps:
      - name: Checkout ffmpeg-build repository
        uses: actions/checkout@v2

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          install: >-
            base-devel
            git
            unzip
            mingw-w64-${{ matrix.env }}-jq
            mingw-w64-${{ matrix.env }}-gcc
            mingw-w64-${{ matrix.env }}-pkg-config
            mingw-w64-${{ matrix.env }}-vapoursynth
            mingw-w64-${{ matrix.env }}-meson
            mingw-w64-${{ matrix.env }}-ninja
            mingw-w64-${{ matrix.env }}-spirv-tools
            mingw-w64-${{ matrix.env }}-spirv-cross
            mingw-w64-${{ matrix.env }}-vulkan
            mingw-w64-${{ matrix.env }}-vulkan-headers
            mingw-w64-${{ matrix.env }}-vulkan-loader
            mingw-w64-${{ matrix.env }}-libdovi
            mingw-w64-${{ matrix.env }}-lcms2
            mingw-w64-${{ matrix.env }}-shaderc
            mingw-w64-${{ matrix.env }}-glslang
            mingw-w64-${{ matrix.env }}-cmake
            mingw-w64-${{ matrix.env }}-python
            mingw-w64-${{ matrix.env }}-nasm
            mingw-w64-${{ matrix.env }}-yasm

      - name: Download FFmpeg
        run: |
          wget https://ffmpeg.org/releases/ffmpeg-6.1.tar.xz
          tar xvf ffmpeg-6.1.tar.xz
        shell: msys2 {0}

      - name: Configure FFmpeg
        run: |
          cd ffmpeg-6.1
          export CFLAGS="-fPIC"
          ./configure --disable-all --disable-gpl --disable-iconv --enable-static --enable-pic --enable-avcodec --enable-avformat --enable-decoder=h264 --enable-decoder=hevc --enable-hwaccel=h264_d3d11va --enable-hwaccel=hevc_d3d11va --enable-hwaccel=h264_dxva2 --enable-hwaccel=hevc_dxva2 --enable-hwaccel=h264_vulkan --enable-hwaccel=hevc_vulkan --enable-hwaccel=h264_cuda --enable-hwaccel=hevc_cuda
        shell: msys2 {0}

      - name: Build FFmpeg
        run: |
          cd ffmpeg-6.1
          make -j$(nproc)
        shell: msys2 {0}

      - name: Install zip utility
        run: pacman -Syu --noconfirm zip
        shell: msys2 {0}

      - uses: vimtor/action-zip@v1.1
        with:
            files: ffmpeg-6.1
            dest: ffmpeg_build.zip

      - name: Upload FFmpeg build
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-build-artifact-windows-${{ matrix.arch }}
          path: ffmpeg_build.zip
